### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by cojack** [fangfufu/Linux-Fake-Background-Webcam#136]
Maybe we can leave this issue open and ppl can share their image concepts?

**Comment by fangfufu** [comment]
Well, there are plenty background images available on Google. The way you wrote your issue is not very descriptive. You are not sharing anything yourself either. I am going to close this ticket for now. If you get around update the description of this ticket, and share something nice, I might leave it open.

**Comment by cojack** [comment]
@fangfufu thank you master for your generosity in thinking of opening this thread once again
